version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes: # https://matsuand.github.io/docs.docker.jp.onthefly/storage/volumes/
      - postgres_volume:/var/lib/postgresql/data
    # restart: always # https://docs.docker.jp/v19.03/config/container/start-containers-automatically.html

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/tangochou
    ports:
      - '5000:5000'
    tty: true # 疑似ターミナル (pseudo-TTY) を割り当て。https://docs.docker.jp/compose/compose-file/index.html#tty
    stdin_open: true # サービスコンテナに標準入力を割り当てて実行するよう設定(https://docs.docker.jp/compose/compose-file/index.html#stdin-open)。
    depends_on:
      - db

volumes:
  postgres_volume:
